name: floweapp

services:

  identity-service:
    image: ${DOCKER_REGISTRY-}identityservice  
    build:
      context: .
      dockerfile: src/Services/IdentityService/Dockerfile
    restart: unless-stopped

    ports:
      - "${IDENTITY_HTTP_PORT}:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}

      ConnectionStrings__DefaultConnection: Server=${SQL_SERVER};Database=${IDENTITY_DB};User Id=${SQL_USER};Password=${SQL_PASSWORD};TrustServerCertificate=True;

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: ${RABBITMQ_PORT}
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}

      Redis__ConnectionString: redis:${REDIS_PORT}

    depends_on:
      rabbitmq:
        condition: service_healthy

      redis:
        condition: service_healthy

    networks:
      - flowers-network

  rabbitmq:
    image: rabbitmq:3-management

    restart: unless-stopped

    ports:
      - "${RABBITMQ_PORT}:5672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    networks:
      - flowers-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped

    command: redis-server --appendonly yes

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - flowers-network

networks:
  flowers-network:
    driver: bridge

volumes:
  rabbitmq-data:
  redis-data:
